/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import control.Controlador;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Zisko
 */
public class Chat extends javax.swing.JFrame {

    Controlador control;
    
    public Chat() {
        initComponents();
    }
    
    public Chat(String username, String pass) {
        initComponents();
        control = new Controlador(this);
        txtArea.setEnabled(false); // El area de mensajes del chat no se debe de poder editar
        txtArea.setLineWrap(true); // Las lineas se parten al llegar al ancho del textArea
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laQuestion = new javax.swing.JLabel();
        txtQuestion = new javax.swing.JTextField();
        txtAnswer = new javax.swing.JTextField();
        buLearn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        txtChat = new javax.swing.JTextField();
        buChat = new javax.swing.JButton();
        laAnswer = new javax.swing.JLabel();
        laSystem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        laQuestion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        laQuestion.setText("Question:");

        txtQuestion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuestionKeyPressed(evt);
            }
        });

        txtAnswer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAnswerKeyPressed(evt);
            }
        });

        buLearn.setText("Learn");
        buLearn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buLearnActionPerformed(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtArea.setRows(5);
        txtArea.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(txtArea);

        txtChat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtChatKeyPressed(evt);
            }
        });

        buChat.setText("Send");
        buChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buChatActionPerformed(evt);
            }
        });

        laAnswer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        laAnswer.setText("Answer:");

        laSystem.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        laSystem.setText("Sistema de Aprendizaje");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(laSystem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAnswer, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(laQuestion))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(laAnswer))
                            .addComponent(txtQuestion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buLearn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtChat, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buChat)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(laSystem)
                        .addGap(76, 76, 76)
                        .addComponent(laQuestion)
                        .addGap(8, 8, 8)
                        .addComponent(txtQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(laAnswer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buLearn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buChat))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buLearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buLearnActionPerformed
        try{
            control.addQuestions((txtQuestion.getText()).toLowerCase(), (txtAnswer.getText()).toLowerCase());
            JOptionPane.showMessageDialog(this, "El robot esta aprendiendo. Muchas Gracias!");
            txtQuestion.setText("");
            txtAnswer.setText("");
        } catch (Exception ex){
            System.out.println("Error al intentar aprender. "+ ex);
        }     
    }//GEN-LAST:event_buLearnActionPerformed

    private void buChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buChatActionPerformed
        try{
            String historial = txtArea.getText();
            String answer = control.sendQuestion((txtChat.getText()).toLowerCase());
            if(historial.equals("")){
                txtArea.setText(answer);
                txtArea.append(System.getProperty("line.separator"));
            }
            else{
                txtArea.setText(historial+answer);
                txtArea.append(System.getProperty("line.separator"));
            }
            
        } catch (Exception ex){
            System.out.println("Error al enviar el mensaje. " + ex);
        }
    }//GEN-LAST:event_buChatActionPerformed

    private void txtQuestionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuestionKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try{
                control.addQuestions((txtQuestion.getText()).toLowerCase(), (txtAnswer.getText()).toLowerCase());
                JOptionPane.showMessageDialog(this, "El robot esta aprendiendo. Muchas Gracias!");
                txtQuestion.setText("");
                txtAnswer.setText("");
            } catch (Exception ex){
                System.out.println("Error al intentar aprender. "+ ex);
            }
        }
    }//GEN-LAST:event_txtQuestionKeyPressed

    private void txtAnswerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnswerKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try{
                control.addQuestions((txtQuestion.getText()).toLowerCase(), (txtAnswer.getText()).toLowerCase());
                JOptionPane.showMessageDialog(this, "El robot esta aprendiendo. Muchas Gracias!");
                txtQuestion.setText("");
                txtAnswer.setText("");
            } catch (Exception ex){
                System.out.println("Error al intentar aprender. "+ ex);
            }
        }
    }//GEN-LAST:event_txtAnswerKeyPressed

    private void txtChatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChatKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try{
                String historial = txtArea.getText();
                String answer = control.sendQuestion((txtChat.getText()).toLowerCase());
                if(!answer.equals("")){
                    if(historial.equals("")){
                        txtArea.setText(answer);
                        txtArea.append(System.getProperty("line.separator"));
                    }
                    else{
                        txtArea.setText(historial+answer);
                        txtArea.append(System.getProperty("line.separator"));
                    }
                    txtChat.setText("");                    
                }
                else{
                    JOptionPane.showMessageDialog(this, "No se que responder enseñame. Gracias!");
                    txtChat.setText("");
                }   
            } catch (Exception ex){
                System.out.println("Error al enviar el mensaje. " + ex);
            }            
        }
    }//GEN-LAST:event_txtChatKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buChat;
    private javax.swing.JButton buLearn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel laAnswer;
    private javax.swing.JLabel laQuestion;
    private javax.swing.JLabel laSystem;
    private javax.swing.JTextField txtAnswer;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtChat;
    private javax.swing.JTextField txtQuestion;
    // End of variables declaration//GEN-END:variables
}
